---
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: modelfull
spec:
  annotations:
    project_name: ccfd
    deployment_version: '0.1'
  name: modelfull
  oauth_key: oauth-key
  oauth_secret: oauth-secret
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: quay.io/odh-workshops/ccfd-business-workflow-tutorial-ccfd-modelfull:1.1-CCFD
          imagePullPolicy: Always
          name: modelfull
          resources:
            requests:
              memory: 10Mi
        terminationGracePeriodSeconds: 20
    graph:
      children: []
      name: modelfull
      endpoint:
        type: REST
      type: MODEL
    name: modelfull
    replicas: 1
    annotations:
      predictor_version: '0.1'
