apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: modelfullservicemonitor
  labels:
    team: opendatahub
spec:
  endpoints:
    - path: /prometheus
      port: http
  selector:
    matchLabels:
      seldon-app: modelfull-modelfull
