---
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: modelfull
spec:
  annotations:
    project_name: ccfd-dev
    deployment_version: '0.1'
  name: modelfull
  oauth_key: oauth-key
  oauth_secret: oauth-secret
  predictors:
  - graph:
      children: []
      implementation: SKLEARN_SERVER
      modelUri: s3://modelfull.joblib
      envSecretRefName: seldon-init-container-secret
      name: modelfull
    name: default
    replicas: 1
